#+TITLE: Emacsism

[[https://www.gnu.org/software/emacs/][Emacs]] + [[https://excersim.org][Excersim]]

A wrapper for exercism [[https://exercism.org/cli-walkthrough][CLI]] and runners.

* Installation

** Manual installation

Clone the repository

#+begin_src sh
  git clone https://github.com/ricardoricho/emacsism
#+end_src

Add to source-list

#+begin_src emacs-lisp
  (add-to-list load-path "Path where clone is.")
#+end_src

Require the package

#+begin_src emacs-lisp
  (require 'emacsism)
#+end_src

** Using straight

#+begin_src emacs-lisp
  (use-package emacsism
    :straight (emacsism :host github :repo ricardoricho/emacsism)
    :bind-keymap (("C-c E" . emacsism-command-map))
    :config
    (emacsism-mode))
#+end_src

* Usage

Emacsism relies on the ~excersism-cli~ package to be installed.
When emacsism activated ~emacsism-mode~ it checks installation and if missing
runs an error. To install ~exercsims-cli~ got to
https://exercism.org/cli-walkthrough

Once installed and required emacsism provide this functions:

  - ~emacsism-url-download-and-open~: Download and open ~Readme.md~ file from
    the URL, example: ~(emacsism-url-download-and-open "URL")~ the function is
    interactive so with: ~M-x emacsism-url-download-and-open~ it asks for the URL.
  - ~emacsism-download-and-open~: Interactive function that ask for the track
    and exercise to download and open ~Readme.md~ file.

  - ~emacsism-find-exercise~: Ask for the track and exercise that already been
    downloaded and open the README.md file of exercise.

  - ~emacsism-test~: Also an interactive function that, when called from a file
    inside the exercise directory, it will run the exercise tests.

* Runners.

When ~emacsism-container-command~ is present, as ~"podman"~ or ~"docker"~ or
similar but not ~nil~. The tests will run ussing the "exercism track
runner". For example, in a rust exercise, the runner is
~exercism/rust-test-runner~, and it will run the test, set the results in a
~json~ file and open the parsed result in a new buffer.
